#define FORCE_COIL_ISENS_ADC2_CONVERSION_ORDER 0
#define ZMOTOR_TACHOMETER_ADC2_CONVERSION_ORDER 1
#define LVDT_A_ADC2_CONVERSION_ORDER 2
#define LVDT_B_ADC2_CONVERSION_ORDER 3

#define VSENS_CONVERSION_ORDER 0
#define ISENS_CONVERSION_ORDER 1
